spring:
  datasource:
    url: jdbc:h2:~/billing
    username: a
    password: a


---
#spring:
#  profiles: prod
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/billing?createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: pablo-1
#    driver-class-name: com.mysql.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop